name: golang-test

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

jobs:
  golang:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: test
      run: go test -v ./...
